// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewGest.Infrastructure.Data;

#nullable disable

namespace NewGest.Infrastructure.Migrations
{
    [DbContext(typeof(NewgestDbContext))]
    partial class NewgestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "cfg");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "cfg");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "cfg");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "cfg");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "cfg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Cnt.Asiento", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("IdComprobanteOrigen")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoAsiento")
                        .HasColumnType("int");

                    b.HasKey("IdAsiento");

                    b.HasIndex("IdComprobanteOrigen");

                    b.HasIndex("IdEmpresa", "Fecha");

                    b.HasIndex("IdEmpresa", "Numero")
                        .IsUnique();

                    b.ToTable("Asientos", "cnt");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Cnt.CuentaContable", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdCuentaPadre")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("ImputaDirectamente")
                        .HasColumnType("bit");

                    b.Property<int>("Naturaleza")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa", "IdCuentaPadre");

                    b.ToTable("CuentasContables", "cnt");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Cnt.PartidaAsiento", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartida"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Debe")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Haber")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.HasKey("IdPartida");

                    b.HasIndex("IdAsiento", "IdCuenta");

                    b.ToTable("PartidasAsiento", "cnt");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComprobante"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<int>("CondicionIvaReceptor")
                        .HasColumnType("int");

                    b.Property<string>("CuitCliente")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedidoOrigen")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocialCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdComprobante");

                    b.HasIndex("IdEmpresa", "Fecha");

                    b.HasIndex("IdEmpresa", "IdCliente");

                    b.HasIndex("IdEmpresa", "Tipo", "PuntoVenta", "Numero")
                        .IsUnique();

                    b.ToTable("Comprobantes", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Imputacion", b =>
                {
                    b.Property<int>("IdImputacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImputacion"));

                    b.Property<int>("IdComprobante")
                        .HasColumnType("int");

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdImputacion");

                    b.HasIndex("IdPago", "IdComprobante");

                    b.ToTable("Imputaciones", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.ItemComprobante", b =>
                {
                    b.Property<int>("IdItemComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItemComprobante"));

                    b.Property<int>("Alicuota")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdComprobante")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("SubtotalNeto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdItemComprobante");

                    b.HasIndex("IdComprobante");

                    b.ToTable("ItemsComprobante", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.ItemPedido", b =>
                {
                    b.Property<int>("IdItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItemPedido"));

                    b.Property<decimal>("CantidadEntregada")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CantidadPedida")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("IdItemPedido");

                    b.HasIndex("IdPedido");

                    b.ToTable("ItemsPedido", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.ItemRemito", b =>
                {
                    b.Property<int>("IdItemRemito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItemRemito"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdRemito")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("IdItemRemito");

                    b.HasIndex("IdRemito");

                    b.ToTable("ItemsRemito", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.MedioPago", b =>
                {
                    b.Property<int>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedioPago"));

                    b.Property<string>("BancoEmisor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("FechaVencimientoCheque")
                        .HasColumnType("date");

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("NumeroCheque")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroTransferencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdMedioPago");

                    b.HasIndex("IdPago");

                    b.ToTable("MediosPago", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.NumeradorComprobante", b =>
                {
                    b.Property<int>("IdNumerador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumerador"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("bigint");

                    b.HasKey("IdNumerador");

                    b.HasIndex("IdEmpresa", "PuntoVenta", "Tipo")
                        .IsUnique();

                    b.ToTable("NumeradoresComprobante", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SaldoAFavor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TotalImputado")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TotalMedios")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdEmpresa", "IdCliente");

                    b.HasIndex("IdEmpresa", "Numero")
                        .IsUnique();

                    b.ToTable("Pagos", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdEmpresa", "Estado");

                    b.HasIndex("IdEmpresa", "IdCliente");

                    b.ToTable("Pedidos", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Remito", b =>
                {
                    b.Property<int>("IdRemito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRemito"));

                    b.Property<DateTime>("FechaRemito")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("IdRemito");

                    b.HasIndex("IdEmpresa", "IdPedido");

                    b.ToTable("Remitos", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Retencion", b =>
                {
                    b.Property<int>("IdRetencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRetencion"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoRetenido")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("NumeroFormulario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdRetencion");

                    b.HasIndex("IdPago");

                    b.ToTable("Retenciones", "com");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Config.AlicuotaRetencion", b =>
                {
                    b.Property<int>("IdAlicuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlicuota"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("TipoRetencion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("IdAlicuota");

                    b.HasIndex("IdEmpresa", "TipoRetencion", "Provincia", "VigenciaDesde")
                        .IsUnique()
                        .HasFilter("[Provincia] IS NOT NULL");

                    b.ToTable("AlicuotasRetencion", "cfg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Config.Parametro", b =>
                {
                    b.Property<int>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametro"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdParametro");

                    b.HasIndex("Clave", "IdEmpresa")
                        .IsUnique()
                        .HasFilter("[IdEmpresa] IS NOT NULL");

                    b.ToTable("Parametros", "cfg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .HasColumnType("CHAR(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Empresas", "cfg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Inv.Deposito", b =>
                {
                    b.Property<int>("IdDeposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDeposito"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("IdDeposito");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.ToTable("Depositos", "inv");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Inv.ExistenciaDeposito", b =>
                {
                    b.Property<int>("IdExistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExistencia"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CostoPromedio")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdDeposito")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("IdExistencia");

                    b.HasIndex("IdArticulo", "IdDeposito")
                        .IsUnique();

                    b.HasIndex("IdEmpresa", "IdArticulo");

                    b.ToTable("ExistenciasDeposito", "inv");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Inv.MovimientoStock", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int?>("IdComprobanteOrigen")
                        .HasColumnType("int");

                    b.Property<int>("IdDeposito")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdArticulo", "FechaMovimiento");

                    b.HasIndex("IdEmpresa", "IdDeposito");

                    b.ToTable("MovimientosStock", "inv");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Articulo", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticulo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("CHAR(15)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("PrecioLista")
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("IdArticulo");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdUnidad");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.ToTable("Articulos", "neg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEmpresa", "CUIT")
                        .HasFilter("[CUIT] IS NOT NULL");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.ToTable("Clientes", "neg");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CUIL")
                        .HasColumnType("CHAR(11)");

                    b.Property<decimal?>("ComisionPorcentaje")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<bool>("EsVendedor")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdEmpresa", "EsVendedor");

                    b.HasIndex("IdEmpresa", "Legajo")
                        .IsUnique();

                    b.ToTable("Empleados", "neg");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.GrupoArticulo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdGrupoPadre")
                        .HasColumnType("int");

                    b.HasKey("IdGrupo");

                    b.HasIndex("IdGrupoPadre");

                    b.HasIndex("IdEmpresa", "Descripcion", "IdGrupoPadre")
                        .IsUnique()
                        .HasFilter("[IdGrupoPadre] IS NOT NULL");

                    b.ToTable("GruposArticulos", "neg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Mutual", b =>
                {
                    b.Property<int>("IdMutual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMutual"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("IdMutual");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique();

                    b.ToTable("Mutuales", "neg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdUnidad");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Unidades", "neg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Viaje", b =>
                {
                    b.Property<int>("IdViaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdViaje"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Destino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaViaje")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("IdViaje");

                    b.HasIndex("IdEmpresa", "FechaViaje");

                    b.ToTable("Viajes", "neg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Users.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "cfg");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DebeResetearPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Legajo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("IdEmpresa", "UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users", "cfg");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewGest.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Cnt.PartidaAsiento", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Cnt.Asiento", null)
                        .WithMany("Partidas")
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Comprobante", b =>
                {
                    b.OwnsOne("NewGest.Domain.Entities.Com.CaeInfo", "Cae", b1 =>
                        {
                            b1.Property<int>("ComprobanteIdComprobante")
                                .HasColumnType("int");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("CaeCodigo");

                            b1.Property<DateOnly>("FechaVencimiento")
                                .HasColumnType("date")
                                .HasColumnName("CaeFechaVencimiento");

                            b1.HasKey("ComprobanteIdComprobante");

                            b1.ToTable("Comprobantes", "com");

                            b1.WithOwner()
                                .HasForeignKey("ComprobanteIdComprobante");
                        });

                    b.Navigation("Cae");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Imputacion", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Com.Pago", null)
                        .WithMany("Imputaciones")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.ItemComprobante", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Com.Comprobante", null)
                        .WithMany("Items")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.ItemPedido", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Com.Pedido", null)
                        .WithMany("Items")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.ItemRemito", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Com.Remito", null)
                        .WithMany("Items")
                        .HasForeignKey("IdRemito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.MedioPago", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Com.Pago", null)
                        .WithMany("Medios")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Retencion", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Com.Pago", null)
                        .WithMany("Retenciones")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.Articulo", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Neg.GrupoArticulo", "Grupo")
                        .WithMany("Articulos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewGest.Domain.Entities.Neg.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.GrupoArticulo", b =>
                {
                    b.HasOne("NewGest.Domain.Entities.Neg.GrupoArticulo", "GrupoPadre")
                        .WithMany("Subgrupos")
                        .HasForeignKey("IdGrupoPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GrupoPadre");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Cnt.Asiento", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Comprobante", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Pago", b =>
                {
                    b.Navigation("Imputaciones");

                    b.Navigation("Medios");

                    b.Navigation("Retenciones");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Com.Remito", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NewGest.Domain.Entities.Neg.GrupoArticulo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Subgrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
